services:
  postgres_db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg_db
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  data: {}